<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE template [
<!ELEMENT template (restaurants,other)>
  <!ELEMENT restaurants (restaurant*)>
    <!ELEMENT restaurant (restaurantName,about,contact,openHours,deliveryDetails,menu)>
      <!ELEMENT restaurantName (#PCDATA)>

    <!ELEMENT about (restaurantDescription,priceRange,cuisineType,restaurantLogo?,restaurantPicture+)>
      <!ELEMENT restaurantDescription (#PCDATA)>
      <!ELEMENT priceRange (#PCDATA)>
      <!ELEMENT cuisineType (#PCDATA)>
      <!ELEMENT restaurantLogo (#PCDATA)>
      <!ELEMENT restaurantPicture (#PCDATA)>

    <!ELEMENT contact (address,phoneContact+,URL)>
      <!ELEMENT address (streetNumber,streetName,streetType,locality,postcode)>
        <!ELEMENT streetNumber (#PCDATA)>
        <!ELEMENT streetName (#PCDATA)>
        <!ELEMENT streetType (#PCDATA)>
        <!ELEMENT locality (#PCDATA)>
        <!ELEMENT postcode (#PCDATA)>
      <!ELEMENT phoneContact EMPTY>
        <!ATTLIST phoneContact lineType (Landline|Mobile) #REQUIRED>
        <!ATTLIST phoneContact contactNumber CDATA #REQUIRED>
      <!ELEMENT URL (#PCDATA)>

    <!ELEMENT openHours (servicePeriod*)>
      <!ELEMENT servicePeriod (day,startTime,endTime)>
        <!ELEMENT day EMPTY>
          <!ATTLIST day dayOfWeek (Monday|Tuesday|Wednesday|Thursday|Friday|Saturday|Sunday) #REQUIRED>
        <!ELEMENT startTime (#PCDATA)>
        <!ELEMENT endTime (#PCDATA)>

    <!ELEMENT deliveryDetails (minimumPrice,deliveryFee)>
      <!ELEMENT minimumPrice (#PCDATA)>
      <!ELEMENT deliveryFee (#PCDATA)>

    <!ELEMENT menu (item*)>
      <!ELEMENT item (itemName,itemDescription,itemType,price,allergens)>
        <!ELEMENT itemName (#PCDATA)>
        <!ELEMENT itemDescription (#PCDATA)>
        <!ELEMENT itemType EMPTY>
          <!ATTLIST itemType dishType (beef|chicken|pork|seafood|vegetarian|vegan) #REQUIRED>
        <!ELEMENT price (#PCDATA)>
        <!ELEMENT allergens (#PCDATA)>

  <!ELEMENT other (#PCDATA)>

    <!ENTITY websiteDesignBy "Website design by: Jay Rovacsek - c3146220">
]>

<template>
  <restaurants>

  <!-- ####################################################### Start of restaurant definition ####################################################### -->

    <restaurant>
      <restaurantName>Saphire Indian</restaurantName>

      <!-- Start of about definition ####################################################### -->
      <about>
        <restaurantDescription>Indian fine dining restaurant located between Merewether and Adamstown offering 5 star food and service, including dine in, takeaway, delivery and catering</restaurantDescription>
        <priceRange>$15-$70</priceRange>
        <cuisineType>Indian</cuisineType>
        <restaurantLogo>https://sapphireindianrestaurant.com.au/wp-content/uploads/2016/05/logo-60px.png</restaurantLogo>
        <restaurantPicture>https://sapphireindianrestaurant.com.au/wp-content/uploads/bb-plugin/cache/img-gallery-028-landscape.jpg</restaurantPicture>
      </about>

      <!-- Start of contact definition, considered extensibility to state/country, but figured that is outside scope of requirements -->
      <contact>
        <address>
          <streetNumber>367-369</streetNumber>
          <streetName>Glebe</streetName>
          <streetType>Road</streetType>
          <locality>Merewether</locality>
          <postcode>2291</postcode>
        </address>
        <phoneContact lineType="Landline" contactNumber="0249632369" />
        <URL>https://sapphireindianrestaurant.com.au/</URL>
      </contact>

      <!-- Start of open hours definition, while singular as required by assignment, children exist to allow entry of multiple days and potentially multiple
           Open hours per day or different segments for breakfast, lunch, dinner, etc -->
      <openHours>
        <servicePeriod>
          <day dayOfWeek="Monday" />
          <startTime>12:00pm</startTime>
          <endTime>10:00pm</endTime>
        </servicePeriod>

        <servicePeriod>
          <day dayOfWeek="Tuesday" />
          <startTime>12:00pm</startTime>
          <endTime>10:00pm</endTime>
        </servicePeriod>

        <servicePeriod>
          <day dayOfWeek="Wednesday" />
          <startTime>12:00pm</startTime>
          <endTime>10:00pm</endTime>
        </servicePeriod>

        <servicePeriod>
          <day dayOfWeek="Thursday" />
          <startTime>12:00pm</startTime>
          <endTime>10:00pm</endTime>
        </servicePeriod>

        <servicePeriod>
          <day dayOfWeek="Friday" />
          <startTime>12:00pm</startTime>
          <endTime>10:00pm</endTime>
        </servicePeriod>

        <servicePeriod>
          <day dayOfWeek="Saturday" />
          <startTime>12:00pm</startTime>
          <endTime>10:00pm</endTime>
        </servicePeriod>

        <servicePeriod>
          <day dayOfWeek="Sunday" />
          <startTime>12:00pm</startTime>
          <endTime>10:00pm</endTime>
        </servicePeriod>
      </openHours>

        <!-- Start of delivery definition, as per requirements of assignment ####################################################### -->
      <deliveryDetails>
        <minimumPrice>$20</minimumPrice>
        <deliveryFee>$10</deliveryFee>
      </deliveryDetails>

        <!-- Start of menu definition, aint that nifty? ####################################################### -->
      <menu>
        <item>
          <itemName>Onion Bhajji</itemName>
          <itemDescription>Onion Bhajis are tasty little onion balls bound together with lightly spiced and fragrant chickpea flour batter</itemDescription>
          <itemType dishType="vegetarian" />
          <price>$12.90</price>
          <allergens>NA</allergens>
        </item>
        <item>
          <itemName>Paneer Shashlik</itemName>
          <itemDescription>Cottage cheese, onion, capsicum and tomatoes grilled to perfection with Smokey and zesty flavours</itemDescription>
          <itemType dishType="vegetarian" />
          <price>$16.90</price>
          <allergens>NA</allergens>
        </item>
        <item>
          <itemName>Zingha Vada</itemName>
          <itemDescription>Black Tiger King Prawns are coated in a light thin batter coated with spices and deep fried</itemDescription>
          <itemType dishType="seafood" />
          <price>$22.90</price>
          <allergens>Seafood</allergens>
        </item>
      </menu>
    </restaurant>

<!--#######################################################DIVIDER TO MAKE THIS EASIER TO READ##########################################################-->

    <restaurant>
      <restaurantName>Raj's Corner</restaurantName>

      <!-- Start of about definition ####################################################### -->
      <about>
        <restaurantDescription>Exquisite, traditional Japanese food with a subtle, contemporary edge; harbourside in the Honeysuckle Precinct of Newcastle.</restaurantDescription>
        <priceRange>$20-$150</priceRange>
        <cuisineType>Japanese</cuisineType>
        <restaurantLogo>http://www.nagisa.com.au/images/system/nagisa-logo.png</restaurantLogo>
        <restaurantPicture>http://www.hunterhunter.com.au/images/nagisa/nagisa-interior.jpg</restaurantPicture>
      </about>

      <!-- Start of contact definition, considered extensibility to state/country, but figured that is outside scope of requirements -->
      <contact>
        <address>
          <streetNumber>200</streetNumber>
          <streetName>Beaumont</streetName>
          <streetType>Street</streetType>
          <locality>Hamilton</locality>
          <postcode>2303</postcode>
        </address>
        <phoneContact lineType="Landline" contactNumber="0249621827" />
        <URL>https://rajscorner.com.au/</URL>
      </contact>

      <!-- Start of open hours definition, while singular as required by assignment, children exist to allow entry of multiple days and potentially multiple
           Open hours per day or different segments for breakfast, lunch, dinner, etc -->
      <openHours>
        <servicePeriod>
          <day dayOfWeek="Monday" />
          <startTime>10:30am</startTime>
          <endTime>10:00pm</endTime>
        </servicePeriod>

        <servicePeriod>
          <day dayOfWeek="Tuesday" />
          <startTime>10:30am</startTime>
          <endTime>10:00pm</endTime>
        </servicePeriod>

        <servicePeriod>
          <day dayOfWeek="Wednesday" />
          <startTime>10:30am</startTime>
          <endTime>10:00pm</endTime>
        </servicePeriod>

        <servicePeriod>
          <day dayOfWeek="Thursday" />
          <startTime>10:30am</startTime>
          <endTime>10:00pm</endTime>
        </servicePeriod>

        <servicePeriod>
          <day dayOfWeek="Friday" />
          <startTime>10:30am</startTime>
          <endTime>10:00pm</endTime>
        </servicePeriod>

        <servicePeriod>
          <day dayOfWeek="Saturday" />
          <startTime>10:30am</startTime>
          <endTime>10:00pm</endTime>
        </servicePeriod>

        <servicePeriod>
          <day dayOfWeek="Sunday" />
          <startTime>10:30am</startTime>
          <endTime>10:00pm</endTime>
        </servicePeriod>
      </openHours>

        <!-- Start of delivery definition, as per requirements of assignment ####################################################### -->
      <deliveryDetails>
        <minimumPrice>$30</minimumPrice>
        <deliveryFee>$0</deliveryFee>
      </deliveryDetails>

        <!-- Start of menu definition, aint that nifty? ####################################################### -->
      <menu>
        <item>
          <itemName>Chicken Karaage</itemName>
          <itemDescription>Fried chicken pieces marinated in soy, ginger and shiokoji with our spicy, pirikara mayonnaise</itemDescription>
          <itemType dishType="chicken" />
          <price>$17</price>
          <allergens>NA</allergens>
        </item>
        <item>
          <itemName>Kabocha Korokke</itemName>
          <itemDescription>Panko crumbed, roast Japanese pumpkin croquettes with ponzu aioli</itemDescription>
          <itemType dishType="vegetarian" />
          <price>$16</price>
          <allergens>NA</allergens>
        </item>
        <item>
          <itemName>Miso Kingfish</itemName>
          <itemDescription>Roast kingfish, organic sweet Meru Miso glaze, sunomono cucumber</itemDescription>
          <itemType dishType="seafood" />
          <price>$22</price>
          <allergens>Seafood</allergens>
        </item>
      </menu>
    </restaurant>

<!--#######################################################DIVIDER TO MAKE THIS EASIER TO READ##########################################################-->

    <restaurant>
      <restaurantName>Surtaj Indian</restaurantName>

      <!-- Start of about definition ####################################################### -->
      <about>
        <restaurantDescription>Located in the heart of Newcastle, you will find our family run restaurant with over 18 years of experience.</restaurantDescription>
        <priceRange>$20-$60</priceRange>
        <cuisineType>Indian</cuisineType>
        <restaurantLogo>http://surtajindianrestaurant.com.au/wp-content/uploads/2012/03/logo23.jpg</restaurantLogo>
        <restaurantPicture>http://surtajindianrestaurant.com.au/wp-content/uploads/2012/03/front1.jpg</restaurantPicture>
      </about>

      <!-- Start of contact definition, considered extensibility to state/country, but figured that is outside scope of requirements -->
      <contact>
        <address>
          <streetNumber>265</streetNumber>
          <streetName>Hunter</streetName>
          <streetType>Street</streetType>
          <locality>Newcastle</locality>
          <postcode>2300</postcode>
        </address>
        <phoneContact lineType="Landline" contactNumber="0249263555" />
        <URL>http://surtajindianrestaurant.com.au/</URL>
      </contact>

      <!-- Start of open hours definition, while singular as required by assignment, children exist to allow entry of multiple days and potentially multiple
      Open hours per day or different segments for breakfast, lunch, dinner, etc -->
      <openHours>
        <servicePeriod>
          <day dayOfWeek="Tuesday" />
          <startTime>11:30am</startTime>
          <endTime>8:00pm</endTime>
        </servicePeriod>

        <servicePeriod>
          <day dayOfWeek="Wednesday" />
          <startTime>11:30am</startTime>
          <endTime>8:00pm</endTime>
        </servicePeriod>

        <servicePeriod>
          <day dayOfWeek="Thursday" />
          <startTime>11:30am</startTime>
          <endTime>8:00pm</endTime>
        </servicePeriod>

        <servicePeriod>
          <day dayOfWeek="Friday" />
          <startTime>11:30am</startTime>
          <endTime>8:00pm</endTime>
        </servicePeriod>

        <servicePeriod>
          <day dayOfWeek="Saturday" />
          <startTime>5:00pm</startTime>
          <endTime>3pm</endTime>
        </servicePeriod>
      </openHours>

      <!-- Start of delivery definition, as per requirements of assignment ####################################################### -->
      <deliveryDetails>
        <minimumPrice>$30</minimumPrice>
        <deliveryFee>$5</deliveryFee>
      </deliveryDetails>

      <!-- Start of menu definition, aint that nifty? ####################################################### -->
      <menu>
        <item>
          <itemName>Beef Rogan Josh</itemName>
          <itemDescription>A beef curry with special herbs and spices, mild.</itemDescription>
          <itemType dishType="beef" />
          <price>$13</price>
          <allergens>NA</allergens>
        </item>
        <item>
          <itemName>Mango Chicken</itemName>
          <itemDescription>Chicken in a creamy mango infused sauce.</itemDescription>
          <itemType dishType="chicken" />
          <price>$16</price>
          <allergens>NA</allergens>
        </item>
        <item>
          <itemName>Prawn Pokora</itemName>
          <itemDescription>Prawns dipped in a spicy chickpea and spice mix.</itemDescription>
          <itemType dishType="seafood" />
          <price>$18</price>
          <allergens>Seafood</allergens>
        </item>
      </menu>
    </restaurant>

  </restaurants>
  <other>&websiteDesignBy;</other>
</template>